name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Baixando Código
        uses: actions/checkout@v4

      - name: 🔐 Autenticando no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: ⚙️ Configurando SDK do Google
        uses: google-github-actions/setup-gcloud@v2

      - name: 🚀 Deploy no Cloud Run
        run: |
          gcloud run deploy prisma \
            --source . \
            --project prisma-501720 \
            --region us-central1 \
            --allow-unauthenticated \
            --memory 4Gi \
            --cpu 4 \
            --port 8080 \
            --timeout 300 \
            --quiet


