name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Baixando Código
        uses: actions/checkout@v4

      - name: 🔐 Autenticando no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: ⚙️ Configurando SDK do Google
        uses: google-github-actions/setup-gcloud@v2

      - name: 🚀 Deploy no Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: prisma
          region: us-central1
          source: .
          flags: '--allow-unauthenticated --memory=2Gi --timeout=120'
          env_vars: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            REDIS_URL=${{ secrets.REDIS_URL }}
            GCS_BUCKET=${{ secrets.GCS_BUCKET }}
            GCS_PREFIX=${{ secrets.GCS_PREFIX }}
            MAX_PARALELAS=${{ secrets.MAX_PARALELAS }}
